### ISSUE TITLE
Not clear for all themes . (wp 4.4.2 ) 

### ISSUE THREAD

**Issue by codevscolor** [AndiDittrich/WordPress.Enlighter#29] opened 2016-02-25 13:59 UTC
![screen shot 2016-02-25 at 7 23 52 pm](https://cloud.githubusercontent.com/assets/15077973/13321562/c018d57a-dbf5-11e5-8efa-2e5a2f95243f.png)

You can see that the texts are much bolder than normal . Is it for any settings mismatched or side effect of any other plugins ? ( i don't have any other code editor plugins installed)

**Comment by AndiDittrich** [comment] 2016-02-25 14:04
Dear codevscolor,

this is an intended behavious of the `Enlighter` Theme. The `keyword1` text is set to bold by default.
you can customize it by using the `Theme Customizer` and set the font-weight to normal

**Comment by codevscolor** [comment] 2016-02-26 05:14
@AndiDittrich : Thank you . But I am not able to use theme customizer. Only blank page is opened. Do i need to change the permission for the directory ? ( You have mentioned about it on one thread )

**Comment by AndiDittrich** [comment] 2016-02-26 19:48
What do you exactly mean with 

> Only blank page is opened

? If you select the theme "WPCustom" a new Tab named "Theme Customizer" should appear on top.

**Comment by codevscolor** [comment] 2016-03-01 06:47
Yes I have reinstalled it and this problem is fixed. But now I am not able to save edited theme style. i.e. after "save changes" is clicked, next if I click on "load theme style" , it moves back to the previous default theme properties. ?

**Comment by AndiDittrich** [comment] 2016-03-01 09:19
it is the intended behaviour: "load theme styles" loads the **default styles** into the Theme Editor.
If you click it again, the styles are set to default again.

**Comment by codevscolor** [comment] 2016-03-01 11:07
Ok..so my settings is :
Appearance-> Theme -> WPCustom
Theme Customizer -> Basic Theme ->Git (this theme i have modified and saved the settings)
Next I have included one code snippet with Theme "Default(Global Settings)" , but it is showing in plain text, not using my customized git theme . What may be the reason ?

**Comment by AndiDittrich** [comment] 2016-03-01 11:27
please send my a link to your page - i will take a look on it

**Comment by codevscolor** [comment] 2016-03-01 11:50
Please check this post

http://codevscolor.com/2016/03/temp-post/

**Comment by AndiDittrich** [comment] 2016-03-01 12:20
well, the generated css file `http://codevscolor.com/wp-content/plugins/enlighter/cache/EnlighterJS.custom.css` is missing - it seems to be a caching issues/error within your webserver configuration. you can try to set the directory permission to `0777`

on the enlighter settings page -> "System Info": is the cache marked as writable ?

**Comment by codevscolor** [comment] 2016-03-01 12:30
Yes. It is marked as true : 
"Cache writeable: true"

**Comment by codevscolor** [comment] 2016-03-01 12:51
Finally.. changing permission to 0777 for cache directory solved this . Thank you for your support.

**Closed** 2016-03-01 20:24 UTC
Labels: question
